version: '3.9'
services:
  tradingo-education-manager:
    container_name: tradingo-education-manager
    image: tradingo/education-manager
    build:
      context: ../tradingo
      dockerfile: education-manager/Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - common.env

  tradingo-membership-manager:
    container_name: tradingo-membership-manager
    image: tradingo/membership-manager
    build:
      context: ../tradingo
      dockerfile: membership-manager/Dockerfile
    restart: unless-stopped
    ports:
      - 8083:8083
    env_file:
      - common.env

  tradingo-generic-client:
    container_name: tradingo-generic-client
    image: tradingo/generic-client
    build:
      context: ../tradingo
      dockerfile: generic-client/Dockerfile
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file:
      - common.env

  tradingo-db:
    container_name: tradingo-db
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=codingDevPwd21
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - ./database:/var/opt/mssql/data


  tradingo-elasticsearch:
    container_name: tradingo-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    restart: unless-stopped
    environment:
      - network.host=0.0.0.0
      - node.name=tradingo-elasticsearch
      - cluster.name=es-docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=tradingo-elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  tradingo-kibana:
    container_name: tradingo-kibana
    image: docker.elastic.co/kibana/kibana:7.12.0
    restart: unless-stopped
    ports:
      - 5601:5601
    environment:
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_URL: http://tradingo-elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://tradingo-elasticsearch:9200"]'
    depends_on:
      - tradingo-elasticsearch

  tradingo-prometheus:
    image: prom/prometheus:latest
    container_name: tradingo-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    user: root
    expose:
      - 9090
    ports:
      - 9090:9090


  tradingo-grafana:
    container_name: tradingo-grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=tradingopwd
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=myrul.com
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=myadrress@gmail.com
      - GF_SMTP_PASSWORD=mypassword
      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com


  tradingo-zookeeper:
    container_name: tradingo-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  tradingo-kafka:
    image: wurstmeister/kafka
    container_name: tradingo-kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://tradingo-kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: tradingo-zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic-test:1:1,add-member:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


#kafka-console-producer.sh --bootstrap-server localhost:9092 --topic topic-test
#kafka-console-consumer.sh --bootstrap-server localhost:9092 --group kafka-group --topic topic-test
#kafka-console-producer.sh --bootstrap-server tradingo-kafka:9093 --topic topic-test
#kafka-console-consumer.sh --bootstrap-server tradingo-kafka:9093 --group kafka-group --topic topic-test
