version: '3.8'
services:
  tradingo-api:
    container_name: tradingo-api
    image: tradingo/api
    build:
      context: ../tradingo-api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8083:8080

  tradingo-postgres:
    container_name: tradingo-postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_URL=jdbc:postgresql://localhost:5432/testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tradingopwd
    ports:
      - 5432:5432

  tradingo-elasticsearch:
    container_name: tradingo-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    restart: unless-stopped
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  tradingo-kibana:
    container_name: tradingo-kibana
    image: docker.elastic.co/kibana/kibana:7.12.0
    restart: unless-stopped
    ports:
      - 5601:5601
    depends_on:
      - tradingo-elasticsearch

  tradingo-prometheus:
    image: prom/prometheus:latest
    container_name: tradingo-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    expose:
      - 9090
    ports:
      - 9090:9090

  tradingo-grafana:
    container_name: tradingo-grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=tradingopwd
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=myrul.com
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=myadrress@gmail.com
      - GF_SMTP_PASSWORD=mypassword
      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com

